name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true


    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-central-1

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7 # Use your preferred version

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 4: Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./terraform

      # Step 5: Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Lint Terraform
        run: tflint
        working-directory: ./terraform

      - name: Ensure write permissions for the directory
        run: chmod -R 777 ./terraform
        working-directory: ./terraform

      - name: Run Checkov
        run: | 
            checkov -d ./terraform -v --output json > checkov_results.json
            echo "Exit code: $?"
        working-directory: ./terraform

      - name: Debug Directory Contents
        run: ls -R ./terraform

      - name: Test Checkov Directly
        run: checkov -d . -v
        working-directory: ./terraform

      - name: Verify Checkov Results
        run: |
          if [ -s ./terraform/checkov_results.json ]; then
            echo "Results file exists and is not empty."
          else
            echo "Results file is empty or does not exist."
          fi
        working-directory: ./terraform

      - name: Display Checkov Results
        run: cat ./terraform/checkov_results.json

      - name: Install Go dependencies
        run: go mod tidy
        working-directory: ./test

      - name: Install Terratest Dependencies
        working-directory: ./test
        run: |
          go mod init github.com/DeepthiMagaji/terraform-module/test || true
          go get github.com/gruntwork-io/terratest/modules/terraform
          go mod tidy

      #terratest
      - name: Run Terratest
        working-directory: ./test
        run: go test -v s3_test.go

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      # Optional Step 7: Terraform Apply
      # Uncomment if you want to apply changes automatically
      #- name: Terraform Apply
      #  run: terraform apply -auto-approve tfplan
